-- phpMyAdmin SQL Dump
-- version 2.10.1
-- http://www.phpmyadmin.net
-- 
-- Host: localhost
-- Generation Time: Apr 05, 2008 at 02:38 AM
-- Server version: 5.0.45
-- PHP Version: 5.2.5

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

-- 
-- Database: `aura_shop`
-- 

-- --------------------------------------------------------

-- 
-- Table structure for table `aboutus`
-- 

CREATE TABLE `aboutus` (
  `id` int(10) unsigned NOT NULL auto_increment,
  `title` varchar(255) NOT NULL,
  `content` text NOT NULL,
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- 
-- Dumping data for table `aboutus`
-- 


-- --------------------------------------------------------

-- 
-- Table structure for table `chakras`
-- 

CREATE TABLE `chakras` (
  `chakra_id` int(10) unsigned NOT NULL auto_increment,
  `title` varchar(255) NOT NULL,
  `content` text NOT NULL,
  PRIMARY KEY  (`chakra_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- 
-- Dumping data for table `chakras`
-- 


-- --------------------------------------------------------

-- 
-- Table structure for table `contact_email`
-- 

CREATE TABLE `contact_email` (
  `email_id` int(10) unsigned NOT NULL auto_increment,
  `email` varchar(255) NOT NULL,
  PRIMARY KEY  (`email_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=3 ;

-- 
-- Dumping data for table `contact_email`
-- 

INSERT INTO `contact_email` (`email_id`, `email`) VALUES 
(1, 'aurashop@aol.com'),
(2, 'crazykaine5391@yahoo.com');

-- --------------------------------------------------------

-- 
-- Table structure for table `copyright`
-- 

CREATE TABLE `copyright` (
  `id` int(10) unsigned NOT NULL auto_increment,
  `year` int(4) NOT NULL,
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=2 ;

-- 
-- Dumping data for table `copyright`
-- 

INSERT INTO `copyright` (`id`, `year`) VALUES 
(1, 2008);

-- --------------------------------------------------------

-- 
-- Table structure for table `crystals`
-- 

CREATE TABLE `crystals` (
  `crystal_id` int(10) unsigned NOT NULL auto_increment,
  `name` text NOT NULL,
  `shakra` text NOT NULL,
  `chemistry` text NOT NULL,
  `description` text NOT NULL,
  `category` varchar(255) NOT NULL,
  `pic` text NOT NULL,
  PRIMARY KEY  (`crystal_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=81 ;

-- 
-- Dumping data for table `crystals`
-- 

INSERT INTO `crystals` (`crystal_id`, `name`, `shakra`, `chemistry`, `description`, `category`, `pic`) VALUES 
(1, 'Agate', 'All Chakras', 'N/A', '<p><strong>Description:</strong><br />\r\n•   Agate is a variegated class of chalcedony;  usually exhibiting colored bands or other markings. However some agate  is not patterned.<br>\r\n  •   Balances yin-yang energies<br>\r\n  •   Stabilizes &amp; cleanses the aura<br>\r\n  •   Acts to smooth dysfunctional energies and to both transform and eliminate negativity<br>\r\n  •   Helpful when examining oneself &amp; the circumstances relevant to their well-being<br>\r\n  •   Can be placed in water for use in cooking and/or for drinking to dispel sickness<br>\r\n  •   Has been used to strengthen sight, diminish thirst, &amp; to promote marital fidelity<br>\r\n  •   Astrological sign of Gemini</p>\r\n<p>These properties are common to all members of the Agate family.  However, each individual type of agate possesses further qualities. Use  your knowledge of color and charkas to enhance the agate properties  listed above accordingly:</p>\r\n<p><strong>Blue Lace Agate: </strong>most useful for throat chakra, communication, calming, etc.</p>\r\n<p>There are most likely hundreds of different agates that have not  been categorized so have fun with them. You might discover one that has  never been seen before.</p>', 'A', 'Agate.jpg'),
(2, 'Alexandrite', 'Solar Plexus, Heart', 'Variety of Chrysoberyl - Beryllium Aluminum Oxide', '<p><strong>Description:</strong><br />\r\n•   Alexandrite is named for the former czar of Russia, Alexander II<br>\r\n•   If genuine, this mineral will exhibit the color green by sunlight and red-violet by artificial light<br>\r\n•   Said to be the most powerful gemstone to escalate spiritual evolution<br>\r\n•   Has regenerative powers<br>\r\n•   Creates a more balanced emotional state<br>\r\n•   Used to rebirth the inner and outer self<br>\r\n•   Assists one in centering the self<br>\r\n•   Reinforces the self esteem<br>\r\n•   Aligns the mental, emotional, and Etheric bodies<br>\r\n•   Brings good fortune to its owner<br>\r\n•   Aids disease of the nervous system, disorders associated with lukemia<br>\r\n•  Astrological signs of Scorpio</p>', 'A', 'Alexandrite.jpg'),
(3, 'Amazonite', 'Heart, Throat', 'KAlSi3 O8\r\n Potassium aluminum silicate', '<p><strong>Description:</strong><br />\r\n•   Also known as Microcline<br>\r\n•   Notable occurrences include Colorado, North Carolina, Russia, Norway, Madagascar <br>\r\n•   A type of feldspar that crystallizes in the form of prismatic crystals, tabular crystals or masses<br>\r\n•   Assists in releasing emotional body grief by helping to express it creatively<br>\r\n•   Helps to release the feeling of a need to suffer<br>\r\n•   Provides pacification and eliminates aggression<br>\r\n•   Soothes all chakras<br>\r\n•   Releases worry and fear<br>\r\n•   Helps to manifest and retain the pure energy of Universal Love<br>\r\n•   Produces a balancing &amp; preventative energy<br>\r\n•   A lovely stone to carry or wear for general health maintenance<br>\r\n•   It balances the female/male energies, bringing forth the qualities of clarity &amp; clear spirit<br>\r\n•   Helps to integrate and synthesize duality<br>\r\n•   Balances the many aspects of one''s personality<br>\r\n•   Improves communication<br>\r\n•   Wonderful relationship stone<br>\r\n•   Heals thymus<br>\r\n•  Astrological sign of Virgo</p>', 'A', 'Amazonite.jpg'),
(4, 'Amethyst', 'Third Eye, Crown', 'SiO2\r\n Silicon dioxide - Variety of Quartz', '<p><strong>Description:</strong><br />\r\n•   Notable occurances include Brazil, Uruguay, Mexico <br>\r\n•   A variety of quartz that forms in crystalline or massive form<br>\r\n•   Known as the ''Stone of Spirituality and Contentment''<br>\r\n•   Facilitates transmutation of lower energies into the higher frequencies of the spiritual and ethereal levels<br>\r\n•   Clears the aura and stabilizes any dysfunctional energy in the body, bestowing stability, strength, &amp; peace<br>\r\n•   An excellent ''Stone of Meditation''<br>\r\n•   Conducts calm and peaceful energy to help enter &amp; maintain the meditative state<br>\r\n•   For humility<br>\r\n•   Assists in surrender and letting go<br>\r\n•   For mental clarity<br>\r\n•   Provides prosperity and helps business affairs to prosper<br>\r\n•   Encourages &amp; supports sobriety, working for one who is attempting to find freedom from addictions<br>\r\n•   Empowers the Crown Chakra<br>\r\n•  Astrological sign of Pisces, Aquarius, &amp; Capricorn</p>', 'A', 'Amethyst.jpg'),
(5, 'Ametrine', 'Third Eye, Crown', 'SiO2\r\n Silicon dioxide - Merging of Citrine & Amethyst', '<p><strong>Description:</strong><br />\r\n•   Notable occurances include Brazil, Uruguay, Mexico <br>\r\n•   A mixing of citrine &amp; amethyst that forms in crystalline or massive form<br>\r\n•   Stabilizes the balance between spirituality and daily life<br>\r\n•   The stone for ''Universal Equilibrium''<br>\r\n•   Stimulates the development of consciousness<br>\r\n•   In meditation &amp; attunement used to reach higher states more quickly<br>\r\n•   Disperses negativity from the aura<br>\r\n•   Facilitates the release of blockages from the physical, emotional, mental, and auric bodies<br>\r\n•   Allows one to recognize the need to eliminate prejudice<br>\r\n•   The amethyst raises the clearing qualities of the citrine to a higher level while expanding the extent of the energy<br>\r\n•   Helpful when one is provided with artificial organs, implants, prosthetics<br>\r\n•  Astrological sign of Libra</p>', 'A', 'Ametrine.jpg'),
(6, 'Angelite', 'Crown', 'CaSO4\r\n Calcium Sulfate', '<p><strong>Description:</strong><br />\r\n•   NAME ORIGIN: From the Greek anhydros, meaning ''waterless''<br>\r\n•   Notable Occurrences include Mexico; Peru; Germany and New Mexico <br>\r\n•   Crystallizes in the form of masses and rarely crystals<br>\r\n•   Known as the ''Stone of Angels''<br>\r\n•   Known as the ''Awareness Stone''<br>\r\n•   Is an excellent balancing agent<br>\r\n•   Provides a protective field around the area where it is placed<br>\r\n•   Use in an elixir to install a shield of protection around the body<br>\r\n•   An excellent stone for both astrological and mathematical understanding and comprehension<br>\r\n•   Links the networks of the ethereal to the physical<br>\r\n•   Represents peace to the world<br>\r\n•   Enhances creativity and psychic ability<br>\r\n•   Increases angelic protection for oneself and ones home<br>\r\n•   For those embarking on a spiritual journey, Angelite is a very valuable friend<br>\r\n•   Used to correct deficiencies of hemoglobin, treat inflammation of throat and thymus<br>\r\n•   Astrological sign of Aquarius</p>', 'A', 'Angelite.jpg'),
(7, 'Apophyllite', 'All Chakras', '(K,Na)Ca4Si8O20(F,OH) - 8H2O\r\n Hydrated Potassium Calcium Silicate Hydroxide Flouride', '<p><strong>Description:</strong><br>\r\n  •   NAME ORIGIN: From the Greek apophylliso - ''it flakes off.''<br>\r\n  •   A pseudo-cubic crystal that is primarily found in India <br>\r\n  •   Creates a conscious connection between the physical form and the spiritual realm<br>\r\n  •   Opens conscious connection to astral body twin, light body &amp; oversoul<br>\r\n  •   Facilitates attunement to ones body as well as to the higher dimensional life forms<br>\r\n  •   Facilitates astral travel<br>\r\n  •   One of the stones that helps one to remain totally conscious while exchanging energy with those of the spirit world<br>\r\n  •   Great for stimulating the intuition and Heart Chakra<br>\r\n  •   Aids decision-making<br>\r\n  •   Provides a cooling energy for physical burns to the body<br>\r\n  •   Aqua Apophyllite, which is uncommon, clears grief &amp; helps release loss and emotional pain<br>\r\n  •   Aqua Apophyllite increases self-forgiveness &amp; forgiveness of others<br>\r\n  •   It increases awareness that the body is only temporary &amp; a small part of the life of the soul<br>\r\n  •   Aqua Apophyllite allows the return of joy, the feeling that "it''s okay"<br>\r\n  •   It stimulates the Thymus<br>\r\n  •  Astrological signs of Libra &amp; Gemini</p>', 'A', 'Apophyllite.jpg'),
(8, 'Aquamarine', 'Throat', 'Be3 Al2 Si6 O18\r\n Variety of Beryl', '<p><strong>Description:</strong><br />\r\n  •   Notable occurrences include Brazil, Pakistan, USA <br>\r\n  •   A variety of Beryl which crystallizes prismatically and rarely terminated<br>\r\n  •   Known as the ''Stone of Courage''<br>\r\n  •   Provides a shielding property for the aura and subtle energy bodies<br>\r\n  •   Comforts in time of physical, emotional, &amp; karmic release<br>\r\n  •   Provides stability for those involved in spiritual development<br>\r\n  •   Ocean Goddess energy<br>\r\n  •   Aids communication &amp; connection with spirit guides &amp; angels<br>\r\n  •   Has been used for improving vision, &amp; assists in the maintenance of the teeth and bone structure<br>\r\n  •   Astrological signs of Gemini, Pisces, Aries</p>', 'A', 'Aquamarine.jpg'),
(9, 'Argonite', 'Sacral', 'CaCO3\r\n Calcium Carbonate', '<p><strong>Description:</strong><br />\r\n•   NAME ORIGIN: Named after its Primary locality; Aragon (Spain)<br>\r\n•    Notable Occurrences include Aragon, Spain, Morocco, France, Sicily,  England, Baja California, Mexico, Tsumeb, Namibia, Austria, Scotland,  and Southwestern United States <br>\r\n•   Crystallizes in the form acicular shaped columnar crystals<br>\r\n•   Useful before a meditation to prep and ground your energy<br>\r\n•   Helpful during periods of stress and anger<br>\r\n•   Bestows discipline and responsibility, patience and acceptance, flexibility and tolerance, reliability, practicality<br>\r\n•   Stabilizes spiritual developments that are moving too fast, that leads to excessive demands or decreased interest<br>\r\n•   Regulates the metabolism of calcium, boosts immune system, helpful when applied locally to the skin<br>\r\n•   Astrological sign of Capricorn</p>', 'A', 'Argonite.jpg'),
(10, 'Azurite', 'Third Eye', 'Variety of Tecktite: Meteoric Silica Glass', '<p><strong>Description:</strong><br />\r\n  •   Notable Occurrences: Moldavia region of Eastern Europe, Thailand and southeast Asia, Australia and Georgia, USA <br>\r\n  •   Tektite is a form of meteoric glass from outer space<br>\r\n  •   Quickens ones spiritual evolution<br>\r\n  •   Carrying a tektite strengthens one''s energy field and manifests positive life change<br>\r\n  •   Moldavite''s high vibrational energy is a powerful chakra opener, particularly at the heart and above<br>\r\n  •   Connects to positive Pleiadian helpers &amp; healers for protection, healing &amp; self healing<br>\r\n  •   Sleeping with moldavite activates the dream states<br>\r\n  •   Accelerates ones'' individual progress by taming the gravitational pull of mass consciousness<br>\r\n  •   Used for direct inter-dimensional accessing of higher dimensional galactic energies<br>\r\n  •   Offers good protection for Earth healers and psychics<br>\r\n  •    Removes negative past life alien implants; protects from negative  alien interference; removes spirit attachments, entities &amp; spirit  possessions<br>\r\n  •   Gives freedom to move among the dimensions &amp; planets while remaining safe on Earth<br>\r\n  •   Acts as a psychic opener and enhancer<br>\r\n  •   Fosters other-planetary contact through dreams &amp; meditation, protects astral travel<br>\r\n  •   Do NOT cleanse with salt<br>\r\n  •   Astrological sign of All - Scorpio predominant</p>', 'A', 'Azurite.jpg'),
(11, 'Black Tourmaline', 'Root', 'NaFe3(Al,Fe)6 Si6O18(BO3)3(OH)4\r\n Sodium Iron Aluminum Boro-silicate Hydroxide', '<p><strong>Description:</strong><br />\r\n•   Notable occurrences include Brazil, Colorado, Appalachian mountains, Germany, England <br>\r\n•   Crystallizes in the form of vertically striated crystals<br>\r\n•   One of the most powerful stones to repel negativity and protect the aura<br>\r\n•    Actually acts as a protective shield, absorbing and transmuting  negative energy, as well as negative thoughts from others, psychic  attacks and spirit possessions<br>\r\n•   Heals fear &amp; panic, bringing a sense of safety &amp; security<br>\r\n•   Activates the ability to ground and remain centered while creating a feeling of welcome on the earth plane<br>\r\n•   Enhances the ability to stay in the body<br>\r\n•   Provides an increase in ones physical vitality, emotional stability, mental clarity and memory<br>\r\n•   Stimulates the reflex points associated with the lower back<br>\r\n•   Grounds in your true life purpose into your heart<br>\r\n•   Astrological sign of Capricorn</p>', 'B', 'BlackTourmaline.jpg'),
(12, 'Blue Calcite', 'Throat', 'CaCO3\r\n Calcium Carbonate', '<p><strong>Description:</strong><br />\r\n  •   NAME ORIGIN: From the Latin, calx, meaning lime<br>\r\n  •   Notable occurances: USA, Brazil, Mexico, Africa <br>\r\n  •   A mineral that forms in masses, grains but is usually cut and polished<br>\r\n  •   An ''energy amplifier''<br>\r\n  •   Heals throat chakra blockages<br>\r\n  •   Supports peaceful assertiveness<br>\r\n  •   Helps the ability to speak one''s needs<br>\r\n  •   Brings inner peace and quiet within<br>\r\n  •   Soothes anger<br>\r\n  •   Connects one to goddess energy<br>\r\n  •   Contributes to beginning spiritual growth<br>\r\n  •   Astrological sign of Cancer</p>', 'B', 'BlueCalcite.jpg'),
(13, 'Blue Chalcedony', 'Throat', 'CaCO3\r\n Calcium Carbonate', '<p><strong>Description:</strong><br />\r\n  •   Chalcedony is considered a member of the quartz family<br>\r\n  •   Occurs as stalactites, botryoidal form, and in the lining of cavities of rocks<br>\r\n  •   Balances the energy of the mind, body, emotions and spirit<br>\r\n  •   Communication, speaking your truth<br>\r\n  •   Encourages ''brotherhood'' among all<br>\r\n  •   Calming and soothing energy<br>\r\n  •   Alleviates hostility, irritability, and melancholy with its nurturing energy<br>\r\n  •   Contributes to knowing oneself<br>\r\n  •   Goddess Energy<br>\r\n  •   Promotes stability within ceremonial activities<br>\r\n  •  Astrological sign of Taurus, Cancer &amp; Leo</p>', 'B', 'BlueChalcedony.jpg'),
(14, 'Calcite', 'All Chakras', 'CaCO3\r\n Calcium Carbonate', '<p><strong>Description:</strong><br />\r\n  •   NAME ORIGIN: From the Latin, calx, meaning lime<br>\r\n  •   Notable occurances: USA, Brazil, Mexico, Africa <br>\r\n  •   A mineral that forms in masses, grains but is usually cut and polished<br>\r\n  •   An ''energy amplifier''<br>\r\n  •   Useful in multidirectional energy distribution<br>\r\n  •   Energy which is directed inward towards the mineral separates and returns at double the intensity<br>\r\n  •   Engenders a spectrum of energy that clears and activates all chakras<br>\r\n  •   Cleanses and acts as a detoxing agent<br>\r\n  •   Can be used to ameliorate improper function of the kidneys, pancreas, and spleen<br>\r\n  •   A balancing agent for assimilation of calcium within the body<br>\r\n  •   Astrological sign of Cancer</p>', 'C', ''),
(15, 'Carnelian', 'Solar Plexus, Heart, Sacral, Root', 'CaCO3\r\n Calcium Carbonate', '<p><strong>Description:</strong><br />\r\n•   Carnelian is a member of the quartz family &amp; usually forms in the uniform color of red, orange, or red-brown<br>\r\n•   Symbolizes the strength and beauty of our planet<br>\r\n•   Grounds attention into the present moment<br>\r\n•   Stimulates analytical capabilities and precision<br>\r\n•   Protects against envy, fear, rage, and helps to banish sorrow from the emotional structure<br>\r\n•   To cleanse negativity from other stones and provides a clearing action when directed in this way<br>\r\n•   Can assist in dramatic pursuits and theatrical presentations<br>\r\n•   Increases physical energy, personal power, creativity &amp; compassion<br>\r\n•   Used for infertility &amp; impotency &amp; cleanses the reproductive organs<br>\r\n•   Rebuilds the Solar Plexus Chakra<br>\r\n•   Self-control, marital happiness &amp; good fortune<br>\r\n•   Astrological sign of Taurus, Cancer &amp; Leo</p>', 'C', 'Carnelian.jpg'),
(16, 'Celestite', 'Third Eye, Throat', 'SrSO4\r\n Strontium Sulfate', '<p><strong>Description:</strong><br />\r\n•   NAME ORIGIN: From the Latin coelestis, meaning ''celestial''.<br>\r\n•   Notable occurrences: Madagascar, Northeastern USA, Sicily, Germany <br>\r\n•   Crystallizes as nodules and tabular crystals<br>\r\n•   Quite good for mental activities, allowing one to recall and to acknowledge spirituality and gifts from the divine<br>\r\n•   For balance, stabilizing the yin-yang values in your aura<br>\r\n•   Fosters connection &amp; ability to work with goddesses, angels, dolphins, fairies &amp; ascended beings<br>\r\n•   Promotes continence in clearing and perfecting the chakras<br>\r\n•   For astral travel and an excellent assistant for dream recall<br>\r\n•   Great crystal for communication &amp; relationships<br>\r\n•   Celestite is an exquisite stone to give in the spirit of love and with the blessing of respect<br>\r\n•   To heal and cleanse areas of pain and chaos into light and love<br>\r\n•   To surrender &amp; get in the flow<br>\r\n•   To treat disorders of the eyes, to increase range of hearing, &amp; to balance mental dysfunctions<br>\r\n•   Astrological sign of Gemini</p>', 'C', 'Celestite.jpg'),
(17, 'Charoite', 'Crown', 'K(Na, Ca)11(Ba, Sr)Si18O46(OH, F)-nH2O\r\n Hydrated Potassium Sodium Calcium Barium Strontium Silicate Hydroxide Fluoride', '<p><strong>Description:</strong><br />\r\n•   NAME ORIGIN: Named for the impression that it gives: ''chary'' in Russian means ''charms'' or ''magic''<br>\r\n•   It is found to date in only one location: along the Chary River at Aldan in Russia <br>\r\n•   Crystallizes in the form of masses and as tiny druse<br>\r\n•   Known as a ''Stone for this Age''<br>\r\n•   Known as a ''Stone of Transformation''<br>\r\n•   Provides for transmutation of negativity and grounding to the spiritual self<br>\r\n•   Bestows vigor, spontaneity, vigor, drive<br>\r\n•   Bestows quiet, refreshing sleep with intense, creative dreams<br>\r\n•   Used to cleanse the auric body<br>\r\n•   Awakens analytical abilities and precision, perceptive observation<br>\r\n•   Sustains ones attention span<br>\r\n•   Helps one to realize that one is, in fact, where one should be during this very moment<br>\r\n•   Helps one to cope with profound change<br>\r\n•   Its popularity would probably be much greater if not for its ''synthetic'' character. It simply looks unnaturally beautiful<br>\r\n•   Helps relieve cramps, calms the nervous system, improves degradation of the liver due to excessive alcohol use<br>\r\n•   Astrological signs of Sagittarius and Scorpio</p>', 'C', 'Charoite.jpg'),
(18, 'Chrysocolla', 'Heart, Throat', 'CuSiO3 - nH2O\r\n Hydrated Copper Silicate', '<p><strong>Description:</strong><br />\r\n  •   NAME ORIGIN: Named from the Greek chrysos -  ''gold'' and kolla - ''glue'' in allusion to the name of the material used  to solder gold<br>\r\n  •   Notable Occurrences include Arizona, Utah, New Mexico and Pennsylvania, Israel, Zaire and England <br>\r\n  •    Occasionally, chrysocolla can have a turquoise color and be used as a  fraudulent substitute for the more precious stone turquoise<br>\r\n  •   Crystallizes in the form of masses and layers<br>\r\n  •   Known as the ''peace stone''<br>\r\n  •   Promotes harmony and expansion<br>\r\n  •   Helps develop the virtues of patience, kindness, tolerance, compassion &amp; humility<br>\r\n  •   For emotional balancing &amp; healing, especially sadness or guilt<br>\r\n  •   Represents goddess energies<br>\r\n  •   Heals all feminine disorders<br>\r\n  •   Further increases ones capacity to love<br>\r\n  •   Supports letting go, forgiveness, surrender, and worry<br>\r\n  •   Purifies the home and the environment<br>\r\n  •   Enhances physical vitality<br>\r\n  •   Used as a ''seeing'' stone for past and future<br>\r\n  •   Used to treat fever, lungs, throat, heart disorders and to balance blood sugar &amp; regulate insulin<br>\r\n  •   Astrological sign of Gemini, Virgo, &amp; Taurus</p>', 'C', 'Chrysocolla.jpg'),
(19, 'Chrysoprase', '', '', ' Please contact us for more information.', 'C', 'Chrysoprase.jpg'),
(20, 'Cinnabar', 'Root', 'HgS\r\n Mercury Sulfide', '<p><strong>Description:</strong><br />\r\n  •   NAME ORIGIN: Of uncertain original meaning, from the Latin, cinnabaris<br>\r\n  •   Notable occurrences include Spain, India, Serbia, China and Southwestern USA <br>\r\n  •   Crystallizes in the form of compact granular masses with needle like crystals<br>\r\n  •   Derived from the Eastern Indian word for ''Dragons Blood''<br>\r\n  •   Stimulates the life force &amp; will to live<br>\r\n  •   Increases one''s drive to succeed and to reproduce<br>\r\n  •   Stimulates dignity, vitality &amp; power<br>\r\n  •   Like Citrine, also a ''Merchants Stone''<br>\r\n  •   Increases alertness by helping one to focus on the earth plane rather than spiritual awareness<br>\r\n  •   Helps to eliminate aggression<br>\r\n  •   Excellent for extracting energy blockages<br>\r\n  •    Used to treat disorders of the blood, provide flexibility in one''s  movement, [yoga] &amp; in the treatment of weight disorders [heulandite  also]<br>\r\n  •   Astrological sign of Leo</p>', 'C', 'Cinnabar.jpg'),
(21, 'Citrine', 'Solar Plexus, Sacral', 'SiO2\r\n Silicon dioxide, Variety of Quartz', '<p><strong>Description:</strong><br />\r\n  •   Notable Occurrences include Arkansas, Brazil <br>\r\n  •   A variety of quartz<br>\r\n  •   Abundance on all levels<br>\r\n  •   Assists in manifesting physical wealth and abundance on all levels<br>\r\n  •   For confidence, inner security and personal power<br>\r\n  •    One of only two minerals on earth that do not hold and accumulate  energy but dissipate and transmute it (Amethyst is the other)<br>\r\n  •   Never needs clearing or cleansing<br>\r\n  •   Activates creativity<br>\r\n  •   Stimulates mental focus, clarity &amp; endurance<br>\r\n  •   Great stone for success in business<br>\r\n  •   Assists in interpersonal relationships or family matters<br>\r\n  •   Helps one to ''laugh'' &amp; to have joy in life<br>\r\n  •   Helps to diminish ''muddy'' areas in your aura while stabilizing anger<br>\r\n  •   Assists in stimulating spiritual power<br>\r\n  •   Aids in digestion, promotes circulation &amp; balances the thyroid gland<br>\r\n  •   Astrological sign of Gemini, Aries, Libra &amp; Leo</p>', 'C', 'Citrine.jpg'),
(22, 'Cobaltian Calcite', 'Heart', 'CoCO3\r\n Cobalt Carbonate, (Sphaerocobaltite)', '<p><strong>Description:</strong><br />\r\n  •   Crystallizes in the form of crusts, spherical masses, rarely crystals<br>\r\n  •   Notable Occurrences include Shaba, Zaire, Saxony Germany and from other secondary cobalt ore locations<br>\r\n  •   One of the most loving members of the mineralogical kingdom<br>\r\n  •   Activates, stimulates, and clears heart chakra<br>\r\n  •   Helps with the formation of friendships<br>\r\n  •   Encourages positivity, dispels negativity<br>\r\n  •   Acts as an energy vortex center, enhancing psychic abilities<br>\r\n  •   Assists one in understanding the cause, effect, and karmic lessons one has/is experiencing<br>\r\n  •    Placement of this mineral on a piece of written material which is  difficult to understand can increase perception of the knowledge wherein<br>\r\n  •   Induces deep relaxation<br>\r\n  •   Generates ideas and solutions<br>\r\n  •   Assists one in reaching Theta state<br>\r\n  •   Balances yin yang energies<br>\r\n  •   Used in the treatment of age related disorders<br>\r\n  •   Astrological sign of Libra</p>', 'C', ''),
(23, 'Coral', 'Solar Plexus, Heart', 'N/A', '<p><strong>Description:</strong><br />\r\n•   The vacated housing of marine animal life<br>\r\n•   Represents continuity, activity &amp; structure<br>\r\n•   Harmonizes one with natural universal forces<br>\r\n•   Balances physical &amp; spiritual realities<br>\r\n•   Supports pregnancy &amp; eases giving birth<br>\r\n•   Alleviates postpartum depression<br>\r\n•   Aids in the new mothers adjustment and bonding to her baby<br>\r\n•   Protects one from depression and despondency<br>\r\n•   Eases baby’s colic and crying<br>\r\n•   Heals adults who were adopted<br>\r\n•   Ideal for inner child healing<br>\r\n•   Astrological sign of Cancer &amp; Libra</p>', 'C', 'Coral.jpg'),
(24, 'Danburite', 'Heart', 'CaB2Si2O8\r\n Calcium boron silicate', '<p><strong>Description:</strong><br />\r\n•   NAME ORIGIN: Named after its location<br>\r\n•   Notable occurrences include Danbury, Connecticut and Russell, New York, Mexico, Japan, Burma &amp; Switzerland <br>\r\n•   Crystallizes in the form of prismatic crystals<br>\r\n•   Intensifies, purifies and magnifies all other healing energies<br>\r\n•   Encourages one to "let your light shine" &amp; helps people to get along with others<br>\r\n•   Activates the heart chakra bringing self-love to the user<br>\r\n•   Increases connection with Angels, Guides, Oversoul, Healers<br>\r\n•   Enhances creativity &amp; mental awareness<br>\r\n•   Used in treatment of gall bladder &amp; liver, &amp; assists in the removal of toxins from the body<br>\r\n•   Astrological sign of Leo</p>', 'D', 'Danburite.jpg'),
(25, 'Dioptase', 'Heart', 'CuSiO3 -H2O\r\n Hydrated copper silicate', '<p><strong>Description:</strong><br />\r\n•   NAME ORIGIN: Named after its location<br>\r\n•   Notable occurrences include Danbury, Connecticut and Russell, New York, Mexico, Japan, Burma &amp; Switzerland <br>\r\n•   Crystallizes in the form of prismatic crystals<br>\r\n•   Intensifies, purifies and magnifies all other healing energies<br>\r\n•   Encourages one to "let your light shine" &amp; helps people to get along with others<br>\r\n•   Activates the heart chakra bringing self-love to the user<br>\r\n•   Increases connection with Angels, Guides, Oversoul, Healers<br>\r\n•   Enhances creativity &amp; mental awareness<br>\r\n•   Used in treatment of gall bladder &amp; liver, &amp; assists in the removal of toxins from the body<br>\r\n•   Astrological sign of Leo</p>', 'D', 'Dioptase.jpg'),
(26, 'Emerald', 'Heart', 'Be3 Al2 Si6 O18\r\n Berylium Aluminum Silicate', '<p><strong>Description:</strong><br />\r\n  •   Notable occurance in Colombia <br>\r\n  •   The green variety of Beryl<br>\r\n  •   Known as the Stone of LOVE &amp; PROSPERITY<br>\r\n  •   Creates ABUNDANCE<br>\r\n  •   Detoxifies negativity and transforms it into positive emotional energy<br>\r\n  •   Security, harmony &amp; closeness to the Goddess within<br>\r\n  •   Aids in emotional &amp; life transitions and changes<br>\r\n  •   To open, activate &amp; stimulate the Heart Chakra<br>\r\n  •   Increases understanding of one''s life purpose in relation to the Universal Plan<br>\r\n  •   Astrology sign of Gemini &amp; Taurus</p>', 'E', 'Emerald.jpg'),
(27, 'Erythrite', '', '', ' Please contact us for more information.', 'E', 'Erythrite.jpg'),
(28, 'Faden', '', '', ' Please contact us for more information.', 'F', 'Faden.jpg'),
(29, 'Fluorite', 'Heart, Sacral', 'CaF2\r\n Calcium Fluoride', '<p><strong>Description:</strong><br />\r\n•   NAME ORIGIN: Named after its composition containing fluorine (Latin, fluere = ''to flow'')<br>\r\n•   Notable occurrences include England, Spain, China, Brazil, Morocco, Canada, Mexico, Germany, and many USA localities<br>\r\n•   Crystallizes in the form of masses, grains, columns, cubes<br>\r\n•   The color range is endless and appears to never be the same<br>\r\n•   Emits an energy to produce order &amp; balance the mental, physical, emotional, creative, &amp; spiritual systems<br>\r\n•   Increases the ability to concentrate while sustaining good health, strong intellect &amp; emotional well being<br>\r\n•   Known as the ''genius stone'' for the highest state of mental achievement<br>\r\n•   Good for the immune system &amp; used in association with colds, flu, staph, strep, cankers, ulcers and similar infections<br>\r\n•   Used to reprogram the Heart Chakra<br>\r\n•   Teaches us to be at one and in a state of peace while remaining individually unique<br>\r\n•   Symbolizes the growth process<br>\r\n•   Purple Fluorite adds spiritual energies to these properties<br>\r\n•    Raspberry Fluorite helps one to initiate the state of  self-fulfillment, bringing to fruition the self-actualizing  characteristics and properties of manifestation<br>\r\n•   Reprograms the  mind at the astral/emotional level, heals the astral body, helps to  bring the astral self/astral twin into the body<br>\r\n•   Aids emotional integration, soothes fear and despair, encourages forgiveness of self and others<br>\r\n•   Accesses the Goddess within; engenders trust in life, self-love, self-empowerment, emotional wholeness<br>\r\n•   Heals heart diseases, headaches, migraines<br>\r\n•   Astrological sign of Pisces and Capricorn</p>', 'F', 'Fluorite.jpg'),
(30, 'Galena', 'Root', 'PbS\r\n Lead Sulfide', '<p><strong>Description:</strong><br />\r\n•   NAME ORIGIN: The Roman naturalist, Pliny, used the name galena to describe lead ore<br>\r\n•   Notable Occurrences include Texas, Oklahoma, Missouri, Germany, Peru, Mexico, Zambia, and England <br>\r\n•   Crystallizes in the form of cubes, masses, &amp; fibers<br>\r\n•   Used to provide grounding<br>\r\n•   Enhances the centering of ones'' energies<br>\r\n•   A ''Stone of Harmony'' stimulating interaction on all levels<br>\r\n•   Decreases self-limiting ideas &amp; patterns<br>\r\n•   Used to reduce inflammation of the skin, to stimulate circulation and hair growth<br>\r\n•   Astrological sign of Capricorn</p>', 'G', 'Galena.jpg'),
(31, 'Garnet', 'Root', 'Ca3Al2(SiO4)3\r\n Calcium Aluminum Silicate', '<p><strong>Description:</strong><br />\r\n•   Notable Occurrences are Asbestos, Canada, Mexico, Kenya, Italy and Sri Lanka <br>\r\n•   Crystallizes in the form of masses, granules, &amp; plate-like layers<br>\r\n•   Garnet is a stone of health, extracting negative energies from the chakras<br>\r\n•   Balances and stimulates the development and movement of the kundalini<br>\r\n•   Opens the Root Chakra and draws earth energy into the body, grounding<br>\r\n•   Aids in changes or disruptions with family and home<br>\r\n•   Assists in manifesting<br>\r\n•   Stimulates the life force, boosts sexuality and fertility<br>\r\n•   Repels disharmonious energies from your aura<br>\r\n•   For treating disorders of the spine, bone, cellular structure, heart, lungs and blood<br>\r\n•   Astrological signs of Leo, Virgo, Capricorn &amp; Aquarius</p>', 'G', 'Garnet.jpg'),
(32, 'Gold', 'Solar Plexus, Crown', 'Au\r\n Elemental gold', '<p><strong>Description:</strong><br />\r\n•   NAME ORIGIN: Anglo Saxon, of uncertain origin<br>\r\n•   Notable occurrences include California and South Dakota, Siberia, Russia, South Africa, Canada <br>\r\n•   Gold has been called ''The Master Healer''<br>\r\n•   Excellent mineral for purification of the physical body<br>\r\n•   Gold emits an energy allowing one''s beauty to come forth<br>\r\n•   The energy of Gold balances the energy fields and eliminates conflicts of ego and feelings of futility<br>\r\n•   Gold combats feelings of depression &amp; inferiority<br>\r\n•   Gold attracts honors, wealth, &amp; happiness while stabilizing the emotional system<br>\r\n•   Gold alleviates tension and stress<br>\r\n•    Gold has been used to treat disorders like arthritis, skin cancer,  pneumonia, heart disease, tuberculosis, &amp; spinal problems<br>\r\n•   Astrological sign of Leo  </p>', 'G', 'Gold.jpg'),
(33, 'Halite', 'Heart, Third Eye, Crown', 'NaCl\r\n Sodium Chloride', '<p><strong>Description:</strong><br />\r\n•   NAME ORIGIN: From the Greek halos, meaning ''salt'' and lithos meaning ''rock.''<br>\r\n•   Notable occurrences include Searles Lake, California, New Mexico &amp; Utah, Germany, and France <br>\r\n•   Crystallizes in the form of masses, columnar structures and cubic crystals<br>\r\n•   Known as "Rock Salt"<br>\r\n•   Cleanse with sunlight NOT water<br>\r\n•   Enhances good will, balances mood swings, diminishes negativity<br>\r\n•   Stimulates acupressure/acupuncture meridians<br>\r\n•   Aids in changing negative thought patterns &amp; bad habits<br>\r\n•   Clears blocks from psychic abilities<br>\r\n•   Removes negativity from one''s spiritual outlook &amp; development<br>\r\n•   Disinfects the aura and chakras<br>\r\n•   Protects those who use alcohol from bringing home bar attachments<br>\r\n•   Used to treat colon &amp; lower intestinal disorders, not to be placed on the abdomen during pregnancy however<br>\r\n•   INDIGO HALITE<br>\r\n•   Stimulates psychic power, mysticism &amp; intuition<br>\r\n•   Encourage adaptability<br>\r\n•   Assimilation of iodine &amp; treatment of thymus, thyroid, thalamus gland<br>\r\n•   Astrological sign of Cancer &amp; Pisces</p>', 'H', 'Halite.jpg'),
(34, 'Hematite', 'Root', 'Fe2O3\r\n Iron Oxide', '<p><strong>Description:</strong><br />\r\n•   NAME ORIGIN: From the Greek, haimatites, ''bloodlike'' in allusion to vivid red color of the powder<br>\r\n•   Notable occurrences include England, Mexico, Brazil, Australia and the Lake Superior region<br>\r\n•   Forms in masses, granular shapes, &amp; botryoidal (uncommon) shapes<br>\r\n•   A ''Stone for the Mind'' that can be used for mental attainment, memory enhancement, original thinking and technical knowledge<br>\r\n•   Harmonizes the yin-yang energies, and balances body, mind, and spirit<br>\r\n•   Revitalizes, grounds and stabilizes ones energies<br>\r\n•   Heals karmic anger and rages while fostering peace and non-aggression<br>\r\n•    Used to stop bleeding and hemorrhaging, to help menstrual flow, and  if placed on the forehead to draw out the heat from fever<br>\r\n•   Used to treat blood disorders, insomnia<br>\r\n•   Aligns the spine<br>\r\n•   Astrological signs of Aries &amp; Aquarius  </p>', 'H', 'Hematite.jpg'),
(35, 'Hemimorphite', 'Throat', 'Zn4Si2O7 (OH)2 - H2O\r\n Hydrated Zinc Silicate Hydroxide', '<p><strong>Description:</strong><br />\r\n•   NAME ORIGIN: Named after the hemimorphic nature of the crystals<br>\r\n•   Notable occurrences: Mexico, New Mexico and New Jersey, England and Zambia <br>\r\n•   Crystallizes as masses, stalactites, boytroidal configurations<br>\r\n•   Used to decrease self-centeredness<br>\r\n•   A ''Stone for Confidence''<br>\r\n•   A ''Stone for self-transformation, evolution''<br>\r\n•   Facilitates the power of self<br>\r\n•   Increases ones self esteem and honest virtues<br>\r\n•   Soothes hostile feelings, anger, resentment<br>\r\n•   Helps one to fully know thyself and reach the highest potential<br>\r\n•   Encourages development of inner strengths<br>\r\n•   An excellent stone for healers; helps to understand the power and benefit of ancient healing techniques<br>\r\n•   Used to ward off poisoning, malice, sooth ulce<br>\r\n•   Provides support for dieting<br>\r\n•   Astrological sign of Libra</p>', 'H', 'Hemimorphite.jpg'),
(36, 'Heulandite', 'Third Eye', '(Ca, Na)(2-3)Al3(Al, Si)2Si13O36 - 12H2O\r\nHydrated Calcium Sodium Aluminum Silicate', '<p><strong>Description:</strong><br />\r\n•   NAME ORIGIN: Named after the English mineral  collector, John Henry Heuland (1778-1856), a British mineral collector  and dealer<br>\r\n•   Notable occurrences include India, Iceland, USA,  Canada, Iran, Italy, Brazil, Australia, New Zealand, Russia, Scotland,  Switzerland <br>\r\n•   Crystallizes in the form of granular masses on other minerals (apophyllite &amp; stilbite)<br>\r\n•    May be used to ''take one back'' to ancient civilizations of Atlantis  &amp; Lemuria where the transfer of ancient information is facilitated<br>\r\n•   Assists in discovery of both the ''old'' and the ''new'', and helps one release the bonds of custom, conceit, and jealousy<br>\r\n•   Holds the energy of centered-ness relative to the loving aspects of the perfect state<br>\r\n•   Enhances weight loss<br>\r\n•   Enables one to recover gracefully after a loss<br>\r\n•   Astrological sign of Sagittarius</p>', 'H', 'Heulandite.jpg'),
(37, 'Iolite', 'N/A', ' Mg2Al4Si5O18\r\n Magnesium Aluminum Silicate - Gemstone variety of Cordierite', '<p><strong>Description:</strong><br />\r\n  •   Crystallizes in the form of masses,  grains, short prismatic crystals<br>\r\n•   Called the "Violet Stone"<br>\r\n•   One of the major stones for use in  attuning Third Eye and Crown Chakras<br>\r\n•   Helps one in the transition toward  spirituality<br>\r\n•   Guides one through spiritual  beginnings<br>\r\n•   Helps release discord from ones life<br>\r\n•   Useful in the elimination of debts<br>\r\n•   Enables one to understand acceptance  of responsibility to the self<br>\r\n•   Promotes excellence in ones  endeavors &amp; the management of money<br>\r\n•   Enhances curiosity, achievement and  growth<br>\r\n•   Physical body detoxifier<br>\r\n•   Used to improve liver disorders,  treat malaria &amp; fever producing disorders<br>\r\n•   Astrological  signs of Libra, Sagittarius &amp; Taurus</p>', 'I', ''),
(38, 'Jade', 'Heart', 'Gem variety of both Jadeite and Nephrite', '<p><strong>Description:</strong><br />\r\n•   NAME ORIGIN: From the Spanish, piedra de ijada,  ''stone of the side,'' because its supposed to cure kidney ailments if  applied to the side of the body<br>\r\n•   Notable Occurrences include Burma, Yunan China, Japan <br>\r\n•   The toughness of jade is remarkable. It has a strength greater than steel<br>\r\n•   The emerald green jade called ''Imperial Jade'' is colored by chromium<br>\r\n•   Known as a ''dream stone'' and ''stone of fidelity''<br>\r\n•   Assists in dream solving and remembering<br>\r\n•   Encourages service to others and the planet<br>\r\n•   Facilitates peace from within the physical, emotional, and intellectual structure<br>\r\n•   Sooths the emotions and heals heart chakra<br>\r\n•   Used to heal heart, kidneys, spleen<br>\r\n•   Use as an elixir to smooth skin and stimulate healthy hair<br>\r\n•   Astrological sign of Aries, Gemini, Libra, &amp; Taurus</p>', 'J', 'Jade.jpg'),
(39, 'Jasper', 'Sacral', 'N/A', '<p><strong>Description:</strong><br />\r\n•   Opaque, forms in massive formations<br>\r\n•   Known as ''the supreme nurturer''<br>\r\n•   Provides protection, protects against negativity<br>\r\n•   Helps one to be grounded<br>\r\n•   Heals women''s anger towards men &amp; calms men''s sexual aggressiveness towards women<br>\r\n•   Balances the yin-yang energies, stabilizes the aura<br>\r\n•   Helpful in times of extended hospital time and when energy is low<br>\r\n•   When fasting, jasper can help to keep energy high<br>\r\n•   Promotes sexual compatibility between lovers, inspires tantric sex<br>\r\n•   Balances sexuality &amp; promotes sexual compatibility<br>\r\n•   Balances menstrual cycles<br>\r\n•   Treatment of internal organs, loss of sense of content in the blood<br>\r\n•   Astrological sign of Leo</p>', 'J', 'Jasper.jpg'),
(40, 'Kyanite', 'Third Eye, Throat', 'Al2SiO5\r\n Aluminum Silicate', '<p><strong>Description:</strong><br />\r\n•   NAME ORIGIN: From the Greek kyanos = ''blue''.<br>\r\n•   Notable occurrences include Brazil, North Carolina, Georgia, Switzerland, Russia, Serbia, India and Kenya <br>\r\n•   Crystallizes in the form of twisted fibrous structures<br>\r\n•   Never needs cleaning or cleansing because it will not accumulate or retain negative energy or vibrations<br>\r\n•   Is UNLIMITED in application making it one of the very best attunement stones<br>\r\n•   Aligns all chakras automatically &amp; immediately with no conscious direction<br>\r\n•   Aids communication physically and psychically<br>\r\n•   Brings tranquility &amp; a calming effect to the whole being<br>\r\n•   Heals blockages &amp; burnout from all auric bodies<br>\r\n•   Facilitates meditation<br>\r\n•   Aids in manifesting in one''s life work on the earth plane<br>\r\n•   Boosts the immune system<br>\r\n•   Used to treat muscular disorders<br>\r\n•   Beneficial to place between heart and solar plexus chakras during healings<br>\r\n•   Astrological signs of Taurus, Libra &amp; Aries</p>', 'K', 'Kyanite.jpg'),
(41, 'Labradorite', 'Third Eye', 'Ca (50-70%) Na (50-30%)\r\n (Al,Si)AlSi2O8\r\n Calcium sodium aluminum silicate', '<p><strong>Description:</strong><br />\r\n•   NAME ORIGIN: Named after its locality Labrador peninsula, Canada <br>\r\n•   Notable Occurrences include Labrador, Canada and Scandinavian Peninsula <br>\r\n•   A mineral that contains a display of spectral colors and rainbow prisms<br>\r\n•    Protects and clears the aura of negative energy, psychic attacks,  negative alien interference, implants, attachments &amp; spirit  possessions<br>\r\n•   Facilitates the transformation of intuition into intellectual thought<br>\r\n•    Symbolizes the moon and the sun energies, providing an added sense of  self during transition, fostering a consciousness of life purpose<br>\r\n•   Aids the ability to see &amp; communicate with positive other world beings<br>\r\n•   Opens the ability for accurate pendulum use &amp; increases psychic vision<br>\r\n•   Used to treat brain disorders, stimulate mental activity<br>\r\n•   Reduces anxiety and stress<br>\r\n•   Astrological signs of Leo, Scorpio &amp; Sagittarius</p>', 'L', 'Labradorite.jpg'),
(42, 'Lapis', 'Third Eye', 'Ca(50-70%) Na(50-30%)\r\n (Al,Si)AlSi2O8\r\n Calcium sodium aluminum silicate', '<p><strong>Description:</strong><br />\r\n•   NAME ORIGIN: From the Persian lazward - ''blue''.<br>\r\n•   Lapis is a combination of lazurite, calcite, and sometimes pyrite<br>\r\n•   Was used as the tablets of the Ten Commandments brought down from Sinai by Moses<br>\r\n•   Stone of total awareness &amp; the symbol of power &amp; royalty<br>\r\n•   Develops and activates intuition<br>\r\n•   Draws the mind inward to seek its own source of power<br>\r\n•   Prevents negative thoughts from becoming karmic patterns<br>\r\n•   Stimulates clarity, emotional and mental purity, and assists in organizing day to day life<br>\r\n•   To overcome depression<br>\r\n•   Brings about success in relationships<br>\r\n•   Protection from physical danger<br>\r\n•   Relief of insomnia, and restructuring physical disorders<br>\r\n•   Astrological sign of Sagittarius</p>', 'L', 'Lapis.jpg'),
(43, 'Larimar', 'Throat', 'NaCa2Si3O8(OH)\r\n Sodium Calcium Silicate Hydroxide - VARIETY OF: Pectolite', '<p><strong>Description:</strong><br />\r\n•   NAME ORIGIN: From the Greek pektos - ''compacted'' and lithos - ''stone''.<br>\r\n•    Larimar, also known as Pectolite, is mined only in the Dominican  Republic &amp; the Bahamas once a year when the volcano is inactive<br>\r\n•   Heals negative karma between soul mates and lovers<br>\r\n•   Fosters honest communication while stabilizing new relationships<br>\r\n•   Helps soul mates to find &amp; recognize each other<br>\r\n•   Calming stone that opens creativity and the Throat Chakra<br>\r\n•   Represents peace &amp; clarity<br>\r\n•   To harmonize the heart &amp; mind<br>\r\n•   Increases sales in business<br>\r\n•   Neutralizes and dissolves old conflicting patterns<br>\r\n•   Cools down fiery energy &amp; calms burning emotions such as anger, frustration, lust &amp; greed<br>\r\n•   Increases personal strength and the ability to say ''no''<br>\r\n•   Associated with Goddess energy<br>\r\n•   To assist in deep meditation &amp; connecting with the angels<br>\r\n•   Stimulates creativity, activates imagination &amp; inspires the spirit<br>\r\n•   Acts as a catalyst in the quest for greater truth &amp; the meaning/purpose in life<br>\r\n•   Opens the acupressure and acupuncture meridians in the feet<br>\r\n•   Astrological sign of Leo</p>\r\n', 'L', 'Larimar.jpg'),
(44, 'Lemurian Seed', 'All Chakras', 'SiO2\r\nSilicon dioxide', '<p><strong>Description:</strong><br />\r\n•   NAME ORIGIN: Lemuria is the name of an ancient civilization believed to have sunk beneath the Pacific Ocean <br>\r\n•   It is said to have pre-dated Atlantis<br>\r\n•   Notable occurrences include Diamantina region of Brazil, famous for its long, tapered laser wands<br>\r\n•   Programmed with the Lemurian consciousness vibrations<br>\r\n•   The crystals can infuse one with the pure emotional/intuitive/spiritual awareness of the Lemurians<br>\r\n•   Heals the emotional body<br>\r\n•   One may feel a return to the soul, a feeling of increased sensuality, and a feminine energy<br>\r\n•   Enhances one''s abilities in channeling and telepathy<br>\r\n•   Enhances meditations and healing work<br>\r\n•   Excellent stone for removing energy blockages<br>\r\n•   Opens the heart and allows for the expression of divine love and compassion</p>', 'L', 'Lemurian.jpg'),
(45, 'Lepidolite', '4th, 5th, 6th, & 7th', 'KLi2Al(Al,Si)3O10(F,OH)2\r\n Potassium lithium aluminum silicate hydroxide fluoride', '<p><strong>Description:</strong><br />\r\n•   NAME ORIGIN: From the Greek lepidion - ''scale'' and lithos - ''stone''<br>\r\n•   Notable Occurrences include Brazil, Ural Mountains, Russia, several African localities and California <br>\r\n•   Crystallizes in the form of masses, short prismatic crystals, plate-like layers, tabular crystals<br>\r\n•   "Stone of Transition"<br>\r\n•   A Lithium mineral, is comprised of approximately 98% Lithium<br>\r\n•   Used for stress reduction and is very calming<br>\r\n•   Assists in restructuring and reorganizing old patterns<br>\r\n•   Enhances life sustaining negative ions in one''s environment<br>\r\n•   Excellent stone for business pursuits<br>\r\n•   Helps one to become open and honest<br>\r\n•   Assists in gardening and agricultural activities aligning the energy forces that produce abundance<br>\r\n•   Used to relieve stress and tension, calming, cramps<br>\r\n•   Astrological signs of Libra</p>', 'L', 'Lepidolite.jpg'),
(46, 'Lithium Quartz', '', '', 'Please contact us for more information.', 'L', 'LithiumQuartz.jpg'),
(47, 'Magnetite', 'Root', 'Fe3O4\r\n Iron Oxide', '<p><strong>Description:</strong><br />\r\n•   Crystallizes in the form of masses and octahedral and rhombdodecahedral crystals which are less magnetic naturally<br>\r\n•   Notable Occurrences include South Africa, Germany, Russia and many localities in the USA <br>\r\n•   Magnetite is a natural magnet, attracting whatever you desire<br>\r\n•   Also known as "Lodestone"<br>\r\n•   Known as the "Stone of Stability"<br>\r\n•   Aligns the chakras<br>\r\n•   Used to attract LOVE and MONEY<br>\r\n•   Extremely instrumental in activities of manifestation<br>\r\n•   Dispels grief, fear, anger and attachment<br>\r\n•   Assists in balancing the emotions with the intellect<br>\r\n•   Encourages trusting intuition in regards to which other crystals and minerals will be beneficial<br>\r\n•   Opens channels that bring about spiritual growth<br>\r\n•   A powerful stone for getting into and maintaining a deep meditative state<br>\r\n•   Helps one attract the healing energies necessary for recovery from disorders<br>\r\n•   Grounds the user into the nurturing energy of the earth<br>\r\n•   The environment of a healer during healing sessions is strengthened and stabilized when using magnetite<br>\r\n•   Attracts tenacity, endurance, durability<br>\r\n•   Used to treat bone structure, skin, hair, nose bleed<br>\r\n•   Astrological sign of Aries, Capricorn, Aquarius &amp; Virgo</p>', 'M', 'Magnetite.jpg'),
(48, 'Malachite', 'Heart', 'Cu2(CO3)(OH)2\r\nCopper Carbonate Hydroxide', '<p><strong>Description:</strong><br />\r\n•   NAME ORIGIN: From the Greek, malache, - ''mallow'' in reference to green leaf color<br>\r\n•    Notable Occurrences include Africa, Russia, Mexico, Australia,  England and several localities in the Southwestern United States  especially in Arizona <br>\r\n•   Malachite forms mostly in masses, ranging in color from light to dark green<br>\r\n•   Stone of transformation, assisting in clearing and activating all chakras<br>\r\n•   An excellent stone for balancing the emotional body<br>\r\n•    Clears and releases trauma by drawing out negative energy  simultaneously bringing to the surface the psychic-emotional roots of it<br>\r\n•   Physical and emotional detoxifier<br>\r\n•   Brings things out from within that may be impeding spiritual growth<br>\r\n•   Used to protect against radiation, poisoning<br>\r\n•   Aids childbirth labor<br>\r\n•   Astrological sign of Capricorn &amp; Scorpio  </p>', 'M', 'Malachite.jpg');
INSERT INTO `crystals` (`crystal_id`, `name`, `shakra`, `chemistry`, `description`, `category`, `pic`) VALUES 
(49, 'Meteorite', 'Heart', 'N/A', '<p><strong>Description:</strong><br />\r\n•   Originates in outer space from the heads of comets, asteroids, mars, the moon<br>\r\n•   Rarer than diamond<br>\r\n•   Represents the energy of other worlds<br>\r\n•    Brings a message from the stars that we on Earth are neither alone  nor abandoned by the Universe, promises that the quarantine of the  planet will end and a time of peace and hope is coming<br>\r\n•   Used for balancing and aligning the bodies<br>\r\n•   Protects energy and aura<br>\r\n•   Grounds, aids in connecting to Earth reality<br>\r\n•   Brings safety and security<br>\r\n•   Evokes positive help from non-Earth sources, aids connection to Pleiadian healers and planetary protectors<br>\r\n•   Makes one a channel for extraterrestrial help for the planet<br>\r\n•   Enhances communication<br>\r\n•   Assists in the actualization of our presence<br>\r\n•   Emits a trusting energy<br>\r\n•   Stone for walk-ins<br>\r\n•   Protects against negative alien interference<br>\r\n•   Attracts guidance from higher dimensions<br>\r\n•   Astrological sign of All</p>', 'M', 'Meteorite.jpg'),
(50, 'Moldavite', 'Heart, Third Eye', 'Variety of Tecktite: Meteoric Silica Glass', '<p><strong>Description:</strong><br />\r\n•   Notable Occurrences: Moldavia region of Eastern Europe, Thailand and southeast Asia, Australia and Georgia, USA <br>\r\n•   Tektite is a form of meteoric glass from outer space<br>\r\n•   Quickens ones spiritual evolution<br>\r\n•   Carrying a tektite strengthens one’s energy field and manifests positive life change<br>\r\n•   Moldavite''s high vibrational energy is a powerful chakra opener, particularly at the heart and above<br>\r\n•   Connects to positive Pleiadian helpers &amp; healers for protection, healing &amp; self healing<br>\r\n•   Sleeping with moldavite activates the dream states<br>\r\n•   Accelerates ones'' individual progress by taming the gravitational pull of mass consciousness<br>\r\n•   Used for direct inter-dimensional accessing of higher dimensional galactic energies<br>\r\n•   Offers good protection for Earth healers and psychics<br>\r\n•    Removes negative past life alien implants; protects from negative  alien interference; removes spirit attachments, entities &amp; spirit  possessions<br>\r\n•   Gives freedom to move among the dimensions &amp; planets while remaining safe on Earth<br>\r\n•   Acts as a psychic opener and enhancer<br>\r\n•   Fosters other-planetary contact through dreams &amp; meditation, protects astral travel<br>\r\n•   Do NOT cleanse with salt<br>\r\n•   Astrological sign of All - Scorpio predominant</p>', 'M', 'Moldavite.jpg'),
(51, 'Moonstone', 'All Chakras, Sacral', 'N/A', '<p><strong>Description:</strong><br />\r\n•   Formed within minerals of the feldspar group<br>\r\n•    The energy of moonstone is capable of helping with the changing  structures of physical, emotional, mental and spiritual levels<br>\r\n•   Increases the intuitional abilities within<br>\r\n•   For hoping and wishing<br>\r\n•   Cleanses negativity from the chakras<br>\r\n•   Brings the white light of healing and the perfection of the rainbow spectrum for activating the chakras<br>\r\n•   Allows for the flow of life information and life movement to the user<br>\r\n•   Enhances the feminine aspects of ones'' nature<br>\r\n•   Soothes and heals the emotions<br>\r\n•   Combines the energies of non-restraint with diligent endurance<br>\r\n•   Acts as a guardian at the gateway to the subconscious<br>\r\n•   Neutralizes fear of feeling<br>\r\n•   Aids spiritual growth, and heals the astral body<br>\r\n•   The stone to attract one''s "King" or "Queen"<br>\r\n•   A symbolic instrument for deciphering the world and its mysteries<br>\r\n•   To regulate menstrual and fertility cycles, and ease menopause<br>\r\n•   Astrological signs of Cancer, Libra &amp; Scorpio</p>', 'M', 'Moonstone.jpg'),
(52, 'Obsidian', 'Root', 'SiO2\r\n Silicon Dioxide with large amounts of impurities', '<p><strong>Description:</strong><br />\r\n•   Notable Occurrences include Italy, Mexico, Scotland, Arizona, Colorado, Texas, Utah and Idaho <br>\r\n•   Obsidian is lustrous volcanic glass<br>\r\n•   An excellent grounding stone<br>\r\n•   Protection from emotional and/or physical harm<br>\r\n•   Provides a shield against negativity and disperses unloving thoughts from the carrier into the mineral<br>\r\n•   Induces creativity in all endeavors<br>\r\n•   Assists in clearing out dirty cobwebs in the deepest recesses of the mind<br>\r\n•   To penetrate the unknown<br>\r\n•   Quite useful in healing the physical body<br>\r\n•   Astrological sign of Sagittarius</p>', 'O', 'Obsidian.jpg'),
(53, 'Okenite', 'Crown', 'CaSi2O4(OH)2 - H2O\r\n Hydrated calcium silicate hydroxide', '<p><strong>Description:</strong><br />\r\n•   NAME ORIGIN: Named after the German natural historian, Lorenz Oken (1779-1851), Munich, Germany <br>\r\n•   Notable Occurrences include Poona, India; Greenland, Chile and Ireland <br>\r\n•   Crystallizes in the form of blade shaped fibrous masses resembling snowballs<br>\r\n•   The energy provides a feeling of ''going home''<br>\r\n•   Opens and clears the light body for connection to the earth, mind, &amp; galactic grids<br>\r\n•   Initiates painless completion and total healing of ones karmic cycle<br>\r\n•   Acts to purify the Chakras and the physical, intellectual, emotional &amp; spiritual bodies<br>\r\n•   Has been used to open oneself to the experience of channeling<br>\r\n•   Has been used to increase blood flow, stimulate circulation in the arms, treat fever &amp; alleviate stomach disorders<br>\r\n•   Good for star people serving on Earth (this stone is not of earthly origin)<br>\r\n•   Astrological sign of Sagittarius &amp; Virgo</p>', 'O', 'Okenite.jpg'),
(54, 'Onyx', 'Crown', 'Variety of CHALCEDONY', '<p><strong>Description:</strong><br />\r\n•   Crystallizes in the form of layers in a variety of colors<br>\r\n•   Centers &amp; aligns the person with the Higher Power<br>\r\n•   Grounds and protects<br>\r\n•   Banishes grief<br>\r\n•   Encourages happiness &amp; good fortune<br>\r\n•   Excellent psychic aid, cleansing intuitive receivers<br>\r\n•   Aids understanding of the cycle of life/death, reinforces the knowledge that there is no death<br>\r\n•   Aids in the understanding of the wheel of birth, death and rebirth<br>\r\n•   Assists in contact with those who have died<br>\r\n•   Aids past-life regression<br>\r\n•   Prevents and removes spirit possessions<br>\r\n•   Helps one to become the Master of their own future<br>\r\n•   Enhances self-control<br>\r\n•   Promotes wise decision making<br>\r\n•   Astrological signs of Leo</p>', 'O', 'Onyx.jpg'),
(55, 'Opal', 'Crown', 'SiO2 - nH2O\r\n Hydrated Silicon Dioxide', '<p><strong>Description:</strong><br />\r\n•   NAME ORIGIN: From the Old Indian upala - ''precious stone''.<br>\r\n•   Crystallizes in the form of masses<br>\r\n•    Viewed via an electron microscope, opal is seen as a uniform stacking  and sizing of a great number of tiny spheres. The particular size of  these spheres determines the color. Colorless opals contains these  spheres also, but without uniform size and stacking<br>\r\n•   Amplifies ones traits and characteristics<br>\r\n•   Furthers clean, true, and spontaneous actions &amp; allows the release of inhibitions<br>\r\n•   Known as a "stone of happy dreams and changes"<br>\r\n•    Awakens psychic and mystical energies<br>\r\n•   Has been used to strengthen memory<br>\r\n•   Instills faithfulness &amp; loyalty in personal &amp; business relationships<br>\r\n•    Used to purify the blood, stimulate circulation, assist in recovery  from Parkinson''s disease, &amp; provide comfort &amp; ease childbirth<br>\r\n•   Astrological signs of Cancer, Libra, Pisces &amp; Scorpio</p>', 'O', 'Opal.jpg'),
(56, 'Peridot', 'Solar Plexus, Heart', '(Mg,Fe)2SiO4\r\n Variety of Olivine', '<p><strong>Description:</strong><br />\r\n•   An estimated 80 - 95% of all world production  of peridot comes from Arizona. Other regions include Egypt, Pakistan,  Brazil, Germany; Chihuahua, Ethiopia, Australia <br>\r\n•   Forms in masses, grains &amp; prismatic crystals<br>\r\n•   Emits a warm and friendly energy<br>\r\n•   To cleanse and stimulate the chakras<br>\r\n•   Heals emotional or nervous tension &amp; physical pain<br>\r\n•   Provides a shield of protection around the body and should be removed prior to any chakra or physical healing<br>\r\n•   Inspires happiness while lessening anger in the ego<br>\r\n•   Promotes complete love, forgiveness and self love<br>\r\n•   Helps heal hurt feelings, bruised egos &amp; damaged relationships<br>\r\n•   To relate to realities beyond the physical world<br>\r\n•   To detox intestinal organs especially the liver<br>\r\n•   To facilitate in the birthing process<br>\r\n•   To strengthen nearsightedness and astigmatism<br>\r\n•   Astrological signs of Virgo, Leo, Scorpio &amp; Sagittarius  </p>', 'P', 'Peridot.jpg'),
(57, 'Pietersite', 'Third Eye', 'N/A', '<p><strong>Description:</strong><br />\r\n•   Only Occurrence: Windhoek, Namibia, Africa <br>\r\n•   Crystallizes in the form of masses, a result of inclusions in jasper which are pseudomorphs after jasper<br>\r\n•   Name Origin: It was discovered by Sid Pieters<br>\r\n•   Said to contain the "keys to the kingdom of heaven"<br>\r\n•   A stone of courage<br>\r\n•   Stimulates the pineal and pituitary glands<br>\r\n•   Aligns the energy centers of the body<br>\r\n•   Held during meditation, grounds the energy to the Etheric body, culminating in access to the akashic records<br>\r\n•   Helps one to recognize their fullest potential<br>\r\n•   Promotes loyalty to the self<br>\r\n•    Regulates the endocrine glands and production of hormones concerned  with growth, sex, metabolism, blood pressure, body temperature<br>\r\n•   Astrological sign of Leo</p>', 'P', 'Pietersite.jpg'),
(58, 'Pyrite', 'Solar Plexus', 'FeS2\r\n Iron Sulfide', '<p><strong>Description:</strong><br />\r\n•   NAME ORIGIN: From the Greek, pyrites lithos,  ''stone which strikes fire,'' in allusion to the sparking produced when  iron is struck by a lump of pyrite<br>\r\n•   Notable Occurrences include Illinois and Missouri, Peru, Germany, Russia, Spain, South Africa <br>\r\n•   Crystallizes in the form of masses with striated cubes<br>\r\n•   Possesses a defending quality, shielding one from negative energies<br>\r\n•   Brings about optimal use of psychic energy<br>\r\n•   Encourages and sustains the ideal of a healthy intellect, &amp; emotional well being<br>\r\n•   Aids prosperity &amp; ability to manifest needs and abundance<br>\r\n•   Uplifts and grounds at once<br>\r\n•   Dispels unwanted interference from both the physical &amp; spiritual worlds<br>\r\n•   Used in the treatment of bronchitis, to stimulate sexuality [when consciously directed] &amp; regulate metabolism<br>\r\n•   Astrological sign of Leo</p>', 'P', 'Pyrite.jpg'),
(59, 'Pyromorphite', 'Root', 'Pb5(PO4)3Cl\r\n Lead Chlorophosphate', '<p><strong>Description:</strong><br />\r\n•   NAME ORIGIN: From the Greek pyr - ''fire'' and morfe - ''form''.<br>\r\n•   Crystallizes in the form of masses, needle like crusts, fibers, grains, hexagonal prisms<br>\r\n•   Notable Occurrences include Idaho and Pennsylvania, Mexico, Germany, England and Australia <br>\r\n•   Used in healing situations, it enhances the energy of the stones in use<br>\r\n•   Aids communication with animals, plants, nature spirits<br>\r\n•   Induces awareness that what harms one harms all<br>\r\n•   A ''Stone for earth Healers''<br>\r\n•   A ''Stone for Victory''<br>\r\n•   Used to release blockages from the acupressure/acupuncture meridians<br>\r\n•   Dispels unwanted microorganisms from the blood<br>\r\n•   Astrological sign of Sagittarius, Leo, Aries</p>', 'P', 'Pyromorphite.jpg'),
(60, 'Quartz', 'All Chakras', 'SiO2\r\n Silicon dioxide', '<p><strong>Description:</strong><br />\r\n•   NAME ORIGIN: From the German ''quarz'', of uncertain origin<br>\r\n•   Notable occurrences include Arkansas, Missouri, Brazil, Uruguay, Mexico, Russia <br>\r\n•   Crystallizes in the form of masses, grains, &amp; prismatic crystals<br>\r\n•   Produces a naturally balanced energy field, modifying the available energy to all areas of the body<br>\r\n•   Harmonizes and aligns all human energies, thoughts, and emotions<br>\r\n•   The natural tendency of quartz is for harmony and is known as the ''Stone of Power''<br>\r\n•   To increase prosperity and abundance in your life<br>\r\n•   Provides for enhanced energy and promotes perseverance, patience and restful sleep<br>\r\n•    If one uses quartz or any other mineral for purposes other than ''for  the good of all'', the experience of destructive forces within one''s  life will be invited<br>\r\n•   The "Stone of Peace"<br>\r\n•   Protects and clears negativity on all levels<br>\r\n•   Clears and activates all chakras<br>\r\n•   Astrological sign of all</p>', 'Q', 'Quartz.jpg'),
(61, 'Quartz with Chlorite', '', '', 'Please contact us for more information.', 'Q', 'QuartzwithChlorite.jpg'),
(62, 'Rhodochrosite', 'Heart', 'MnCO3\r\n Manganese Carbonate', '<p><strong>Description:</strong><br />\r\n•   NAME ORIGIN: From the Greek rhodon -''rose'' and chroma - ''color''.<br>\r\n•   Notable occurrences include USA, Peru, Germany, South Africa, Canada <br>\r\n•   Crystallizes in the form of masses, grains, columns, crusts<br>\r\n•   Known as "The Stone Of Love And Balance"<br>\r\n•   Creates new worlds for the user – worlds filled with love and dreams<br>\r\n•   Reprograms the emotional body to receive joy, heals the ability to give and receive<br>\r\n•   Heals blocks to spiritual energy<br>\r\n•   Cleanses the Heart chakra and heals self-blame<br>\r\n•   When meditating with this stone an encounter with ones twin soul[s] is highly likely<br>\r\n•   Assists in releasing suffering from past and present<br>\r\n•   Opens blocked ability to know/manifest one''s life purpose and karmic agreements<br>\r\n•   Heals lack of connection to Goddess Energy<br>\r\n•   Acts to cleanse and renew<br>\r\n•   Removes tendencies towards avoidance or denial<br>\r\n•   Provides a gentle balancing effect at the Etheric level<br>\r\n•   Beneficial to prevent sickness<br>\r\n•   Prevents emotional sources of cancer from manifesting<br>\r\n•   Astrological signs of Scorpio &amp; Leo</p>', 'R', 'Rhodochrosite.jpg'),
(63, 'Rhodonite', 'Heart', '(Mn,Fe,Mg,Ca)5(SiO3)5\r\n Manganese Iron Magnesium Calcium Silicate', '<p><strong>Description:</strong><br />\r\n•   NAME ORIGIN: From the Greek rhodon -''rose''<br>\r\n•    Notable Occurrences include Ural Mountains, Russia, Broken Hill,  Australia, Langban, Sweden, Minas Gerais, Brazil and Massachusetts and  New Jersey <br>\r\n•   Balances yin yang energy<br>\r\n•   Helps one to attain a calm assurance in all activities<br>\r\n•   Helps one to achieve his/her greatest potential<br>\r\n•   Stimulates, clears and activates heart chakra while grounding at the same time<br>\r\n•   Stimulates the serving aspect of one’s nature and encourages generosity of spirit<br>\r\n•   Facilitates attention to details and interrelationships<br>\r\n•   Promotes maturity in love affairs and relationships (aids in distinguishing real from fantasy)<br>\r\n•   Grounds emotional flights into earth plane reality<br>\r\n•   Helps in recognizing real from wishful in relationships (for those who fall in love too fast and too often)<br>\r\n•   Stimulates alignment of chakras and removal of blockages<br>\r\n•   Used to treat emphysema, inflammations, arthritis<br>\r\n•   Astrological signs of Taurus</p>', 'R', 'Rhodonite.jpg'),
(64, 'Rose Quartz', 'Heart', 'SiO2\r\n Silicon Dioxide - Variety of Quartz', '<p><strong>Description:</strong><br />\r\n•   Notable occurrences include Madagascar, India, Germany, South Dakota, Brazil <br>\r\n•   Crystallizes in the form of masses, grains, and quite rarely as crystal structures<br>\r\n•    The ''stone of gentle love'', rose quartz reinstates the loving gentle  forces of self-love by reprogramming the heart to love itself<br>\r\n•   Brings peacefulness and calm to relationships<br>\r\n•   For spiritual attainment to the energy of love<br>\r\n•   Balances yin-yang energy while tuning each chakra to its proper vibrational frequency<br>\r\n•   Provides an excellent energy for healing emotional wounds &amp; negative childhood experiences<br>\r\n•   Stimulates the true life force: love!<br>\r\n•   For fertility<br>\r\n•   To reduce wrinkles and clear the skin resulting in a soft complexion<br>\r\n•   Astrological sign of Taurus and Libra</p>', 'R', 'RoseQuartz.jpg'),
(65, 'Ruby', 'Heart', 'Al2O3\r\n Silicon Dioxide Variety of Quartz', '<p><strong>Description:</strong><br />\r\n•   NAME ORIGIN: Probably derived from the Sanskrit, kuruvinda, meaning ''ruby''.<br>\r\n•    Notable occurrences include Thailand, India, Madagascar, Zimbabwe,  North Carolina, Afghanistan, Pakistan, Sri Lanka, Kenya, Tanzania,  Kampuchea, and perhaps most notably, Burma<br>\r\n•   Oriented rutile crystal inclusions cause a six-rayed-star light effect (called asterism) to form the popular Star Ruby<br>\r\n•   Known as "Star of Purity"<br>\r\n•   Induces stability in ones economic status<br>\r\n•   It has been said, as long as one retains a little bit of ruby, wealth will never depart<br>\r\n•   Protects against unhappiness, nightmares, and lightning<br>\r\n•   Aids connection to angels, spirit guides, goddesses<br>\r\n•   Fosters channeling &amp; automatic writing<br>\r\n•   Stabilizes, revitalizes energy on all levels &amp; grounds<br>\r\n•   Aids chronic fatigue, weakness, low vitality<br>\r\n•   Astrological signs of Scorpio, Leo, Cancer, Sagittarius</p>', 'R', 'Ruby.jpg'),
(66, 'Rutilated Quartz', 'All Chakras', 'TiO2 & SiO2\r\n Titanium Oxide & Silicon dioxide', '<p><strong>Description:</strong><br />\r\n•   NAME ORIGIN: From the Latin, rutilus - ''reddish''.<br>\r\n•   Notable Occurrences include Minas Gerias, Brazil, Swiss Alps, Arkansas, and some African localities<br>\r\n•    Rutilated Quartz is quartz terminated by rutile, which is a needle  like crystal with a wide color range, commonly yellow, gold, copper and  sometimes silver<br>\r\n•   It is likened to the appearance of wheat straw and Angel Hair<br>\r\n•   The Rutile intensifies the power of the Quartz<br>\r\n•   Repels negativity<br>\r\n•   Stabilizes relationships, marriages, mental processes and emotional &amp; physical imbalances<br>\r\n•   Eases one who is in transition<br>\r\n•   Brings forth calm, reason, &amp; order<br>\r\n•   Astrological signs of Gemini &amp; Taurus</p>', 'R', 'RutilatedQuartz.jpg'),
(67, 'Scolecite', 'Crown', 'CaAl2Si3O10 - 3H2O\r\n Hydrated calcium aluminum silicate Chemistry', '<p><strong>Description:</strong><br />\r\n•   NAME ORIGIN: From the Greek, skolec = ''worm''<br>\r\n•   Notable Occurrences include Poona, India; Riverside Co., California; Iceland; Skye Scotland and Santa Catarina, Brazil <br>\r\n•   Crystallizes in the form of slender prismatic crystals<br>\r\n•   Opens the network of informational patterns to facilitate communication with other dimensions<br>\r\n•   Serves to support the transformation of the heart to love<br>\r\n•   Useful in boosting and aiming the energy of another crystal energy to the point where it is intended<br>\r\n•   Used currently as a stone for extra terrestrial communication<br>\r\n•   Enables one to exhibit control over ones life<br>\r\n•   Astrological sign of Capricorn</p>', 'S', 'Scolecite.jpg'),
(68, 'Smokey Quartz', '', '', 'Please contact us for more information.', 'S', 'SmokeyQuartz.jpg'),
(69, 'Spirit Quartz', 'Crown', 'SiO2\r\n Silicon dioxide - Variety of Quartz', '<p><strong>Description:</strong><br />\r\n•   Variety of Quartz found exclusively in Magaliesburg, South Africa <br>\r\n•    2nd stage mineral growth: the center point of amethyst covered with  Druse Amethyst sometimes doused with ametrine, citrine or smoky<br>\r\n•   Atlantean and Lemurian in origin with ET influences<br>\r\n•   Place one of these rare majestic crystals above your head near your crown chakra to direct energy toward the ethereal planes<br>\r\n•   Opens the crown chakra<br>\r\n•   Recharges and cleanses the aura<br>\r\n•   Used to recognize and diagnose energy blocks<br>\r\n•   Opens inner child energy blocks<br>\r\n•   Creates a youthful feeling of joy and happiness<br>\r\n•   Opens the heart of spirituality<br>\r\n•   Allows the authentic self to emerge parallel with the higher self<br>\r\n•   Integrates all bodies, all selves<br>\r\n•   Astrological sign of All</p>', 'S', 'SpiritQuartz.jpg'),
(70, 'Staurolite', 'Third Eye\r\n', 'Fe2Al9Si4O22(OH)2\r\n Iron Aluminum Silicate Hydroxide', '<p><strong>Description:</strong><br />\r\n•   NAME ORIGIN: Named after its location<br>\r\n•   Notable Occurrences: Tennessee, Georgia, Virginia and Montana, Brazil, Scotland, Italy, France, Russia <br>\r\n•   Crystallizes in the form of flat prismatic crystals with cruciform twinning<br>\r\n•   Known as the ''Fairy Stone''<br>\r\n•   Is a talisman of good luck<br>\r\n•   Said to be the crystallized tears of fairies formed when they were brought the news of the death of Christ<br>\r\n•   Aligns and balances the communication &amp; connection between physical, astral &amp; spiritual planes<br>\r\n•   Provides relief in stressful situations<br>\r\n•   Helpful to alleviate depression &amp; addictive tendencies<br>\r\n•   Provides incentive, initiative, and support to those who are quitting smoking<br>\r\n•   Used to treat fever, depression, malaria<br>\r\n•   Astrological sign of Pisces</p>', 'S', 'Staurolite.jpg'),
(71, 'Stibnite', 'Root', 'Sb2S3\r\n Antimony Sulfide', '<p><strong>Description:</strong><br />\r\n•   NAME ORIGIN: From the Greek, stimmi or stibi,  ''antimony,'' thence to the Latin, stibium. Also from the Greek anthemon,  ''flower'' in allusion to the form of crystal druses<br>\r\n•   Crystallizes in the form of masses, columns blades, needle like crystals with vertical striations<br>\r\n•   Notable Occurrences include Hunan province, China, Japan, Germany, Brazil, Peru and South Africa <br>\r\n•   Used in meditation, it creates an undistracted entry into the meditative state<br>\r\n•   Enhances the energy field<br>\r\n•   Acts as an impenetrable barrier around the physical body<br>\r\n•   Assists in the manifestation of courage<br>\r\n•   A ''Stone to stabilize one''s economy''<br>\r\n•   Used to bring fidelity to relationships<br>\r\n•   Increases understanding between the user and the animal and plant kingdoms<br>\r\n•   Used to treat disorders of the stomach<br>\r\n•   To dispel possession in the body<br>\r\n•   Relieves stiffness in the body<br>\r\n•   Astrological sign of Scorpio &amp; Capricorn</p>', 'S', 'Stibnite.jpg'),
(72, 'Sugilite', 'Root, Crown', 'KNa2Li3(Fe, Mn, Al)2Si12O30\r\n Potassium Sodium Lithium Iron Manganese Aluminum Silicate', '<p><strong>Description:</strong><br />\r\n•   Notable Occurrences include Japan as well as Quebec, Canada and most importantly, South Africa <br>\r\n•   Crystallizes in the form of lightly banded masses and rarely as tiny crystals<br>\r\n•   Color ranges from lavender, violet pink to purple<br>\r\n•   Found mainly in the Kalahari Region of the Republic of South Africa <br>\r\n•   Has surfaced now to bring special healing powers to humanity<br>\r\n•   Helps the spiritual being to live well on the earth plane<br>\r\n•   Cushions the earth''s harshness for spiritually orientated beings<br>\r\n•   The ''love stone for this age'' representing the perfection of spiritual love<br>\r\n•   Archangel Michael''s stone<br>\r\n•   Creates a flow from the crown to the root chakra, opening the chakras and providing a pathway for the movement of kundalini<br>\r\n•   Aids living in the present rather than dwelling in the past or future<br>\r\n•   Tunes ones'' vibration to that of the earth, grounding<br>\r\n•   Balances the left &amp; right hemispheres of the brain<br>\r\n•   Reminds one of the reasons for being in the physical body, to answer the question ''Why am I here?''<br>\r\n•   Releases &amp; heals despair, hostility, eases discouragement<br>\r\n•   Helps one to believe in oneself<br>\r\n•   Sugilite says, ''your presence is very important here and you are loved by the forces of life itself.''<br>\r\n•   Brings peace and relaxation to the user<br>\r\n•   Excellent remedy for headache, dyslexia, stroke &amp; epilepsy<br>\r\n•   Astrological sign of Virgo</p>', 'S', 'Sugilite.jpg'),
(73, 'Tanzanite', 'Third Eye, Crown, Throat', 'Ca2Al3(SiO4)3(OH)\r\n Calcium Aluminum Silicate Hydroxide - VARIETY OF: Zoisite', '<p><strong>Description:</strong><br />\r\n•   NAME ORIGIN: Named after its locality, from Tanzania <br>\r\n•   Discovered in 1967<br>\r\n•   Crystallizes in the form of crusts and prismatic crystals<br>\r\n•   Known as "a stone of magic"<br>\r\n•   Opens chakras for new spiritual awareness promoting interest in metaphysics<br>\r\n•   Opens an awareness of living more consciously<br>\r\n•   Cleanses the emotional body<br>\r\n•   Brings together aspects of expression and psychic vision, allowing the user to adequately communicate insight<br>\r\n•   The energy reaches through the crown chakra for protection and safety during all activities<br>\r\n•   Facilitates meditation &amp; communication with the spiritual world<br>\r\n•   Used to assist one when encountering different aspects of the self<br>\r\n•   Aids in making spiritually influenced life choices<br>\r\n•   Used to treat misalignment of the spinal column, disorders of the eyes, and helps to bring one out of a comatose state<br>\r\n•   Astrological sign of Sagittarius, Leo, Pisces</p>', 'T', 'Tanzanite.jpg'),
(74, 'Tigers Eye', 'Solar Plexus', 'N/A', '<p><strong>Description:</strong><br />\r\n•   Tigers eye is a form of crocidolite (blue  asbestos), always a form of quartz that gets its distinctive yellow and  golden brown stripes from inclusions of iron oxide<br>\r\n•   South Africa is responsible for practically all the tigers eye production in the world<br>\r\n•   Makes one invisible from negative energy sources<br>\r\n•   Promotes courage and self confidence, especially with change<br>\r\n•   Protects travelers from accidents<br>\r\n•   Synthesizes the energies of the Sun &amp; the Earth<br>\r\n•   Enhances psychic abilities<br>\r\n•   Provides for balancing of yin-yang energies<br>\r\n•   Clears negative energy from the Solar Plexus<br>\r\n•   Astrological sign of Capricorn</p>', 'T', 'TigersEye.jpg'),
(75, 'Tourmaline', 'Heart', 'Na(Li,Al)3Al6Si6O18(BO3)3(OH)4\r\n Sodium Lithium Aluminum Boro-Silicate Hydroxide', '<p><strong>Description:</strong><br />\r\n•   Notable Occurrences include San Diego, Brazil, Elba, Italy (where Elbaite gets its name) Sri Lanka, Pakistan, Maine, Russia <br>\r\n•   Forms in vertically striated prismatic crystals<br>\r\n•   Brings deeply comforting love energy and heals the entire emotional body, opening the heart<br>\r\n•    Emanates the message to, ''align yourself with the forces of light  &amp; channel that radiance onto your world and into your life.''<br>\r\n•   Allows one to trust and bring forth the feelings of joy and enthusiasm for life<br>\r\n•   Promotes self love, complete love, compassion for oneself<br>\r\n•   Promotes a lifetime of service, opening the ability to reach out to others<br>\r\n•   Heals &amp; removes heart scars<br>\r\n•   Brings pre-life karmic agreements &amp; life purpose into one''s heart<br>\r\n•   Grounds &amp; removes blockages and negativity from the aura and chakras (black tourmaline)<br>\r\n•   Bridges Heaven &amp; Earth by lowering high spiritual frequencies and raising the frequency of denser matter<br>\r\n•   Assists in the attainment of peace, awareness and universal love<br>\r\n•   To treat disorders of the heart and skin<br>\r\n•   Astrological sign of Libra</p>', 'T', 'Tourmaline.jpg'),
(76, 'Turquoise', 'Throat', 'CuAl6(PO4)4(OH)8 - 5(H2O)\r\n Hydrated Copper Aluminum Phosphate', '<p><strong>Description:</strong><br />\r\n•   Notable Occurrences include Arizona and New Mexico, Australia, Iran, Afghanistan and other localities in the Middle East <br>\r\n•   Forms mostly in masses<br>\r\n•   Strengthens all chakras, connecting and aligning energies<br>\r\n•   Connects physical and spiritual awareness while developing inner strength and calmness<br>\r\n•   Heals Throat Chakra blocks, sadness, and karmic guilt<br>\r\n•   A stone of earth grounding<br>\r\n•   A healer of the spirit, providing a soothing energy and bringing peace of mind<br>\r\n•   Enhances communication &amp; creativity<br>\r\n•   To heal the emotional body<br>\r\n•   To increase circulation<br>\r\n•   Relieves headaches<br>\r\n•   Astrological sign of Sagittarius, Pisces &amp; Scorpio</p>', 'T', 'Turquoise.jpg'),
(77, 'Unakite', 'Solar Plexus, Heart', 'Mottled rock consisting of mainly pink Feldspar, green Epidote, and Quartz.', '<p><strong>Description:</strong><br />\r\n•   Crystallizes in the form of masses<br>\r\n•   Brings the emotional body into alignment with the higher forces of spirituality<br>\r\n•   Clears toxic emotions and old pains<br>\r\n•   Releases anger, resentment, vengeances<br>\r\n•   Helps one to deal with the events or information from the past which have instilled blockages in our energy<br>\r\n•   Used to help one go beneath the physical symptom of disease and determine the root cause underlying the condition<br>\r\n•   Used in treatment of the reproductive system, to stimulate healthy pregnancies<br>\r\n•   Astrological sign of Scorpio  </p>', 'U', 'Unakite.jpg'),
(78, 'Vanadanite', 'Sacral', 'Pb5(VO4)3Cl\r\n Lead Chlorovanadate', '<p><strong>Description:</strong><br />\r\n•   NAME ORIGIN: Named for its vanadium content<br>\r\n•   Notable occurrences: Arizona, Mexico, Tsumeb, Nambia, Zambia, and South Africa <br>\r\n•   Crystallizes as globular masses, barrel shaped crystals, &amp; hollow prismatic crystals<br>\r\n•   Inspires the ability to let go, surrender, &amp; receive the higher purpose<br>\r\n•   Promotes order in one''s life<br>\r\n•   Assists in the grounding/centering process<br>\r\n•   Balances women''s reproductive hormones<br>\r\n•   Promotes thrift in spending<br>\r\n•   A good stone for those who tend to overspend<br>\r\n•   Has been used to regulate menstrual cycles &amp; aids in PMS<br>\r\n•   Shrinks &amp; eliminates tumors &amp; cysts in reproduction organs<br>\r\n•   Treats exhaustion &amp; aids the circulatory system<br>\r\n•   Astrological sign of Virgo</p>', 'V', 'Vanadanite.jpg'),
(79, 'Vivianite', '', '', 'Please contact us for more information.', 'V', 'Vivianite.jpg'),
(80, 'Wulfenite', 'Sacral', 'PbMoO4\r\n Lead Molybdate', '<p><strong>Description:</strong><br />\r\n•   NAME ORIGIN: Named after the Austrian mineralogist, F. X. Wulfen (1728-1805)<br>\r\n•   Crystallizes as the form of masses, octahedral crystals, prismatic, square tabby crystals<br>\r\n•   Notable Occurrences include Morocco, Tsumeb, Nambia, Mexico, Arizona, New Mexico <br>\r\n•   Helps one to let go of the fact that negative aspects exist on this plane<br>\r\n•   Brings order out of confusion in relationships<br>\r\n•   Promotes contact with the spiritual world<br>\r\n•   Facilitates the knowledge and practice of white magic<br>\r\n•   Sponsors a powerful connection to the Higher Self<br>\r\n•   Used for preservation and rejuvenation on all levels<br>\r\n•   Astrological sign of Sagittarius</p>', 'W', 'Wulfenite.jpg');

-- --------------------------------------------------------

-- 
-- Table structure for table `events`
-- 

CREATE TABLE `events` (
  `event_id` int(10) unsigned NOT NULL auto_increment,
  `title` varchar(255) NOT NULL,
  `date` date NOT NULL,
  `content` text NOT NULL,
  `misc` text NOT NULL,
  PRIMARY KEY  (`event_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- 
-- Dumping data for table `events`
-- 


-- --------------------------------------------------------

-- 
-- Table structure for table `mission`
-- 

CREATE TABLE `mission` (
  `id` int(10) unsigned NOT NULL auto_increment,
  `content` text NOT NULL,
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=2 ;

-- 
-- Dumping data for table `mission`
-- 

INSERT INTO `mission` (`id`, `content`) VALUES 
(1, 'AURA SHOP is your resource center for self-awareness and self-empowerment, providing the highest quality products and services. The AURA SHOP vision is to teach clients how to balance their physical, mental, emotional and spiritual energy, while providing an interactive holistic environment with tools and services for personal growth.\r\n<br />\r\nThe AURA SHOP promotes peace and harmony of body, mind and spirit, serving and guiding our clients to know and empower themselves.');

-- --------------------------------------------------------

-- 
-- Table structure for table `news`
-- 

CREATE TABLE `news` (
  `news_id` int(10) unsigned NOT NULL auto_increment,
  `title` varchar(255) NOT NULL,
  `author` varchar(255) NOT NULL,
  `date` datetime NOT NULL,
  `content` text NOT NULL,
  PRIMARY KEY  (`news_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=3 ;

-- 
-- Dumping data for table `news`
-- 

INSERT INTO `news` (`news_id`, `title`, `author`, `date`, `content`) VALUES 
(1, 'Launch of the new Aura Shop website!', 'Webmaster', '2008-02-22 15:17:18', 'Welcome to the newly redesigned website for the Aura Shop.  We still offer all the same great services and products, only now we have a more user-friendly website with some more features.  Look around and feel free to contact us for more information.'),
(2, 'The site is still under construction.', 'Webmaster', '2008-04-04 21:32:42', 'We apologize for the construction on the new site.  We will have all features up and running in a short while.  Thanks for stopping by and be sure to visit the shop if you have a chance in Santa Monica, CA.');
