<?php
# ----------------------------------------------------
# -----
# ----- This script was generated by PHP-Form Wizard 1.2.5 on 4/6/2008 at 1:23:38 AM
# -----
# ----- http://www.tools4php.com
# -----
# ----------------------------------------------------


// Receiving variables
@$pfw_ip= $_SERVER['REMOTE_ADDR'];
@$item = addslashes($_POST['item']);
@$description = addslashes($_POST['description']);
@$category = addslashes($_POST['category']);
@$picture = addslashes($_POST['picture']);
@$MAX_FILE_SIZE = addslashes($_POST['MAX_FILE_SIZE']);

function RecursiveMkdir($path)
 {
   if (!file_exists($path)) 
   { 
      RecursiveMkdir(dirname($path));
      mkdir($path, 0777);
    }
  }


// Validation
if (strlen($item) == 0 )
{
die("<p align='center'><font face='Arial' size='3' color='#FF0000'>An item name is required.</font></p>");
}

if (strlen($description) == 0 )
{
die("");
}

if (strlen($category) == 0 )
{
die("");
}

//saving record to MySQL database


@$pfw_strQuery = "INSERT INTO `newarrivals`(`item`,`description`,`category`,`picture`)VALUES (\"$item\",\"$description\",\"$category\",\"$picture\")" ;
@$pfw_host = "localhost";
@$pfw_user = "root";
@$pfw_pw = "";
@$pfw_db = "aura_shop";
$pfw_link = mysql_connect($pfw_host, $pfw_user, $pfw_pw);
if (!$pfw_link) {
 die('Could not connect: ' . mysql_error());
}
$pfw_db_selected = mysql_select_db($pfw_db, $pfw_link);
if (!$pfw_db_selected) {
die ('Can not use $pfw_db : ' . mysql_error());
}

//insert new record
$pfw_result = mysql_query($pfw_strQuery);
if (!$pfw_result) {
 die('Invalid query: ' . mysql_error());
}
mysql_close($pfw_link);

 echo("<p align='center'><font face='Arial' size='3' color='#FF0000'>The item has been added successfully into the database.</font></p>");
?>
